title: Gürhan Camgöz 
description: Researcher - Multimedia Artist
show_downloads: true
google_analytics:
theme: jekyll-theme-midnight
url: https://gurhan-camgoz.github.io
imagesurl: "/assets/images/"
thumbsurl: "/assets/thumbs/"